language: java
jdk:
  - oraclejdk7
script: 
        - mvn clean test -DCACHE=true -Dtest=CacheTest -B
        - mvn clean test -B
        - mvn cobertura:cobertura
install: 
        mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B       
after_success: 
  - bash <(curl -s https://codecov.io/bash)
  
branches:
  only:
    - match-mybatis-3.3.x