language: java
jdk:
  - oraclejdk7
install: 
        - mvn clean test -DCACHE=true -Dtest=CacheTest -B
after_install: 
        - mvn cobertura:cobertura
after_success:
  - bash <(curl -s https://codecov.io/bash)
  
branches:
  only:
    - match-mybatis-3.3.x