language: java
jdk:
  - oraclejdk7
  - openjdk7
  
install: 
        - mvn install -DCACHE=true -Dtest=CacheTest
before_install: 
        - mvn cobertura:cobertura
after_success:
  - bash <(curl -s https://codecov.io/bash)
  
branches:
  only:
    - match-mybatis-3.3.x